apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi
  namespace: fastapi
spec:
  project: default
  source:
    repoURL: 'https://github.com/Viney-Vean/argocd-config-repo.git' # The Git repository URL
    targetRevision: HEAD
    path: 'overlays/dc' # Path to your production manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'fastapi' # Target namespace in your production cluster
  syncPolicy:
    automated:
      prune: true # Automatically delete resources removed from Git
      selfHeal: true # Automatically revert unauthorized changes back to the Git state
    syncOptions:
      - CreateNamespace=true