apiVersion: v1
kind: Service
metadata:
  name: fastapi-msv-hello-world
  labels:
    app: fastapi-msv-hello-world
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30010
      protocol: TCP
      name: http
  selector:
    app: fastapi-msv-hello-world
  type: LoadBalancer   # MetalLB will assign external IP
